### ISSUE TITLE
is this a wrong approach to use the plugin? background activity doesn't triggers

### ISSUE THREAD

**Issue by JuanCAlpizar** [christocracy/cordova-plugin-background-notification#1]
I'm developing an iOS and android application using phonegap build 3.3 and jQuery mobile 1.4.2.

In android I'm using a different plugin, and app works perfectly on the background, however that one was asking me to turn on location services in iOS, so I decided to test this one.

As a result, at the moment the code doesn't executes in background. My code setup is a bit similar to the sample on readme

```
update_interval = setInterval(function () {
        $.when(phonegap_ready).then(function () {
            alert('engine ready');
            background = window.plugins.backgroundNotification;
            background_callback = function (notification) {
                if (application_storage.getItem('refresh') !== 'never') {
                    result = $.serviceCall('ReportSvc/Mobile/getOpenBets/', 'ID=' + user_token + '&wagerType=' + application_storage.getItem('type') + '&sportType=' + application_storage.getItem('sport') + '&playerid=' + application_storage.getItem('customer'));
                    current_total_bets = result.length;
                    new_bets = current_total_bets - previous_total_bets;
                    alert('time frame');
                } else {
                    window.plugin.notification.badge.clear();
                    clearInterval(update_interval);
                    background.finish();
                    return;
                }

                if (new_bets >= 0) {
                    window.plugin.notification.badge.set(15);
                }

                previous_total_bets = result.length;
                background.finish();
            };

            background.configure(background_callback);
        });
    }, update_check);
```

However the requests to the server are never being called, is there a mistake on the implementation?

**Comment by christocracy** [comment]
I don’t know or care anything about requests to your server being called.

What I would care about, is do you see the following log-entry in iOS log,
when your app receives a Push notification in the background:
- CDVBackgroundNotification onNotification

On Fri, May 2, 2014 at 4:26 PM, JuanCAlpizar notifications@github.comwrote:

> I'm developing an iOS and android application using phonegap build 3.3 and
> jQuery mobile 1.4.2.
> 
> In android I'm using a different plugin, and app works perfectly on the
> background, however that one was asking me to turn on location services in
> iOS, so I decided to test this one.
> 
> As a result, at the moment the code doesn't executes in background. My
> code setup is a bit similar to the sample on readme
> 
> update_interval = setInterval(function () {
>         $.when(phonegap_ready).then(function () {
>             alert('engine ready');
>             background = window.plugins.backgroundNotification;
>             background_callback = function (notification) {
>                 if (application_storage.getItem('refresh') !== 'never') {
>                     result = $.serviceCall('ReportSvc/Mobile/getOpenBets/', 'ID=' + user_token + '&wagerType=' + application_storage.getItem('type') + '&sportType=' + application_storage.getItem('sport') + '&playerid=' + application_storage.getItem('customer'));
>                     current_total_bets = result.length;
>                     new_bets = current_total_bets - previous_total_bets;
>                     alert('time frame');
>                 } else {
>                     window.plugin.notification.badge.clear();
>                     clearInterval(update_interval);
>                     background.finish();
>                     return;
>                 }
> 
> ```
>             if (new_bets >= 0) {
>                 window.plugin.notification.badge.set(15);
>             }
> 
>             previous_total_bets = result.length;
>             background.finish();
>         };
> 
>         background.configure(background_callback);
>     });
> }, update_check);
> ```
> 
> However the requests to the server are never being called, is there a
> mistake on the implementation?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/christocracy/cordova-plugin-background-notification/issues/1
> .

## 

Chris Scott
Transistor Software http://www.transistorsoft.com

**Comment by christocracy** [comment]
I haven’t touched this code in 3 months, and it continues to work solid for
me in other apps.

There’s not really much in the native code which can go wrong.

On Fri, May 2, 2014 at 4:34 PM, Chris Scott christocracy@gmail.com wrote:

> I don’t know or care anything about requests to your server being called.
> 
> What I would care about, is do you see the following log-entry in iOS log,
> when your app receives a Push notification in the background:
> - CDVBackgroundNotification onNotification
> 
> On Fri, May 2, 2014 at 4:26 PM, JuanCAlpizar notifications@github.comwrote:
> 
> > I'm developing an iOS and android application using phonegap build 3.3
> > and jQuery mobile 1.4.2.
> > 
> > In android I'm using a different plugin, and app works perfectly on the
> > background, however that one was asking me to turn on location services in
> > iOS, so I decided to test this one.
> > 
> > As a result, at the moment the code doesn't executes in background. My
> > code setup is a bit similar to the sample on readme
> > 
> > update_interval = setInterval(function () {
> >         $.when(phonegap_ready).then(function () {
> >             alert('engine ready');
> >             background = window.plugins.backgroundNotification;
> >             background_callback = function (notification) {
> >                 if (application_storage.getItem('refresh') !== 'never') {
> >                     result = $.serviceCall('ReportSvc/Mobile/getOpenBets/', 'ID=' + user_token + '&wagerType=' + application_storage.getItem('type') + '&sportType=' + application_storage.getItem('sport') + '&playerid=' + application_storage.getItem('customer'));
> >                     current_total_bets = result.length;
> >                     new_bets = current_total_bets - previous_total_bets;
> >                     alert('time frame');
> >                 } else {
> >                     window.plugin.notification.badge.clear();
> >                     clearInterval(update_interval);
> >                     background.finish();
> >                     return;
> >                 }
> > 
> > ```
> >             if (new_bets >= 0) {
> >                 window.plugin.notification.badge.set(15);
> >             }
> > 
> >             previous_total_bets = result.length;
> >             background.finish();
> >         };
> > 
> >         background.configure(background_callback);
> >     });
> > }, update_check);
> > ```
> > 
> > However the requests to the server are never being called, is there a
> > mistake on the implementation?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/christocracy/cordova-plugin-background-notification/issues/1
> > .
> 
> ## 
> 
> Chris Scott
> Transistor Software http://www.transistorsoft.com

## 

Chris Scott
Transistor Software http://www.transistorsoft.com

**Comment by JuanCAlpizar** [comment]
Sorry maybe I didn't explain it correctly. I posted the code cause the only documentation is an example, and I wanted to make sure the plugin was implemented correctly.

Sadly phonegap build uses to disconnect me before 5 mins which is the lower time frame for the app to enter the interval so I can't check the console, however after the 5 mins I'm getting the "engine ready" (outside callback function) but I'm not getting the "time frame" alert (inside the callback function) the condition is met, the application storage is permanent and I checked the value, also server calls are functional.

So my point was if the plugin is instantiated correctly, or if should I modify the way I'm using it, specially cause you say it's working in another apps.

I'm testing with a physical iPhone 4S with iOS 7.1.1, and developing with phonegap build 3.3 and jQuery Mobile 1.4.2

Thanks for your reply and your time :)

UPDATE: I'll try to look for a way to extend the session in the phonegap build or get the log after the time and I'll update it when I get it.

**Comment by christocracy** [comment]
If your app receives a push notification while running in background,
the callback you send to the #configure function is called.

Simple as that.

On Friday, May 2, 2014, JuanCAlpizar notifications@github.com wrote:

> Sorry maybe I didn't explain it correctly. I posted the code cause the
> only documentation is an example, and I wanted to make sure the plugin was
> implemented correctly.
> 
> Sadly phonegap build uses to disconnect me before 5 mins which is the
> lower time frame for the app to enter the interval so I can't check the
> console, however after the 5 mins I'm getting the "engine ready" (outside
> callback function) but I'm not getting the "time frame" alert (inside the
> callback function)
> 
> So my point was if the plugin is instantiated correctly, or if should I
> modify the way I'm using it, specially cause you say it's working in
> another apps.
> 
> I'm testing with a physical iPhone 4S with iOS 7.1.1, and developing with
> phonegap build 3.3 and jQuery Mobile 1.4.2
> 
> Thanks for your reply and your time :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/christocracy/cordova-plugin-background-notification/issues/1#issuecomment-42082486
> .

## 

Snet from Gmail Mobile
