### ISSUE TITLE
Is this plugin working in Android?

### ISSUE THREAD

**Issue by roboza** [christocracy/cordova-plugin-background-notification#2]
I am trying to use this plugin on android. I have included the plugin but when I try and call it it tells me: Uncaught TypeError: Cannot call method 'configure' of undefined

Any suggestions?

**Comment by christocracy** [comment]
no, iOS only.

On Thu, Jun 26, 2014 at 12:57 PM, robertoswald notifications@github.com
wrote:

> I am trying to use this plugin on android. I have included the plugin but
> when I try and call it it tells me: Uncaught TypeError: Cannot call method
> 'configure' of undefined
> 
> Any suggestions?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christocracy/cordova-plugin-background-notification/issues/2
> .

## 

Chris Scott
Transistor Software http://www.transistorsoft.com

**Comment by christocracy** [comment]
Sorry, I think i responded to wrong thread.  Works for both Android & ios

On Friday, June 27, 2014, robertoswald notifications@github.com wrote:

> Closed #2
> https://github.com/christocracy/cordova-plugin-background-notification/issues/2
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christocracy/cordova-plugin-background-notification/issues/2#event-135758697
> .

## 

Snet from Gmail Mobile

**Comment by markdegrootnl** [comment]
@christocracy Which is it? I don't think this plugin works for Android. The android platform section of plugin.xml is empty. Also there is no src/android.

**Comment by christocracy** [comment]
yup, iOS only.

On Mon, Sep 1, 2014 at 4:03 PM, Mark de Groot notifications@github.com
wrote:

> @christocracy https://github.com/christocracy Which is it? I don't
> think this plugin works for Android. The android platform section of
> plugin.xml is empty. Also there is no src/android.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christocracy/cordova-plugin-background-notification/issues/2#issuecomment-54088648
> .

## 

Chris Scott
Transistor Software http://www.transistorsoft.com

**Comment by markdegrootnl** [comment]
Thanks for the reply. Any change on an Android implementation in the near future?

**Comment by christocracy** [comment]
This is not possible for Android due to the nature of the OS and how it
handles the foreground Android Activity, which can be killed when the OS
requires memory, therefore _executing a js callback is never guaranteed to
run._

On Mon, Sep 1, 2014 at 4:16 PM, Mark de Groot notifications@github.com
wrote:

> Thanks for the reply. Any change on an Android implementation in the near
> future?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christocracy/cordova-plugin-background-notification/issues/2#issuecomment-54089269
> .

## 

Chris Scott
Transistor Software http://www.transistorsoft.com
