### ISSUE TITLE
Plugin not showing up in window.plugins?

### ISSUE THREAD

**Issue by 0x07dc** [christocracy/cordova-plugin-background-notification#4]
I'm trying to use this plugin with cordova 5 and version 3.6.3 of the cordova android platform.

The installation went fine and it's listed with `cordova plugin ls`, however in the app, `window.plugins.backgroundNotification` does not exist nor does anything similar exist.

Is there a platform version requirement for this?

**Comment by christocracy** [comment]
Show me your code.  I bet you're trying to access the plugin before deviceready fires.

Did you try booting the console and inspecting window.plugins?

**Comment by 0x07dc** [comment]
Yeah, that's what I checked. In the console, I only have a few items in `window.plugins` and there's no background anything. 

The code is really simple, it runs on the device ready callback (and the plugin isn't available in `window.plugins` from the console either, even a while after the app has started).

```
    ....
    ....
    onDeviceReady: function() {
        app.receivedEvent('deviceready');
    },
    // Update DOM on a Received Event
    receivedEvent: function(id) {
        var BGN = window.plugins.backgroundNotification;

        // Your background-fetch handler.
        var notificationCallback = function(notification) {
            console.log('BackgroundNotification received');
            BGN.finish();
        }
        BGN.configure(notificationCallback);
    }
    ....
```

**Comment by christocracy** [comment]
- iOS 8, Cordova 5
- I built this plugin on Cordova 3.x.

Everything works as expected.

![ScreenShot](https://www.dropbox.com/s/9fxx3h0smgteyvp/Screenshot%202015-06-19%2011.06.04.png?dl=1)

**Comment by 0x07dc** [comment]
Could you confirm that it works in Android? Thanks

**Comment by christocracy** [comment]
There is no Android
https://github.com/christocracy/cordova-plugin-background-notification/blob/master/plugin.xml#L20
— this plugin is iOS-only.  Android *doesn’t need *a plugin to handle Push
notifications in the background.

On Fri, Jun 19, 2015 at 12:05 PM, recursion1122 notifications@github.com
wrote:

> Could you confirm that it works in Android? Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/christocracy/cordova-plugin-background-notification/issues/4#issuecomment-113558300
> .

## 

Chris Scott
Transistor Software http://www.transistorsoft.com
