### ISSUE TITLE
Can I use this plugin along with your background geolocation plugin?

### ISSUE THREAD

**Issue by seatechdev** [christocracy/cordova-plugin-background-notification#6]
I need to send notifications based on the user location.  Can I use this plugin instead of a push notification.  I have a web service that will crate notification text that will need to be sent while the app is running in the background.  Please advise.

**Comment by christocracy** [comment]
This is a push notification plugin.  However, it's abandoned.

Use phonegap-plugin-push.  It will operate in the bg

On Tuesday, July 5, 2016, Joti basi notifications@github.com wrote:

> I need to send notifications based on the user location. Can I use this
> plugin instead of a push notification. I have a web service that will crate
> notification text that will need to be sent while the app is running in the
> background. Please advise.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/christocracy/cordova-plugin-background-notification/issues/6,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAA6l_DQ337hpgdMskR0Fn-v9rA2n7Pfks5qSdk2gaJpZM4JEw25
> .

## 

Snet form Gmail Mobile
