### ISSUE TITLE
Build failed on PhoneGap

### ISSUE THREAD

**Issue by terraloader** [christocracy/cordova-plugin-background-notification#9]
Log shows the following error:

/Plugins/org.transistorsoft.cordova.background-notification/CDVBackgroundNotification.m:8:9: fatal error: 'Cordova/CDVJSON.h' file not found

Any solution for this? Or do you need more information?

**Comment by christocracy** [comment]
Don't use this repo.  It's been obsolete for >4 years.  `cordova-plugin-push` has implemented everything in this now.
